Add MIP21 contracts interfaces
makerdao/dss-interfaces pull request #75
Opened 2022-07-20 13:26 UTC by hbarcelos

Adds the interfaces for MIP21 contracts from the [`mip21-toolkit`](https://github.com/clio-finance/mip21-toolkit) repo.

**NOTICE**: `clio-finance/mip21-toolkit` will be moved to `makerdao/mip21-toolkit` shortly. GitHub will handle redirections for a while, however we will need to come back and update the references to the contract files when that is done.

2022-07-21 15:32 UTC, godsflaw requested changes

2022-07-21 15:32 UTC, godsflaw commented on src/dss/mip21/RwaLiquidationOracleAbstract.sol
> +    function cull(bytes32) external;
```suggestion
    function cull(bytes32, address) external;
```

2022-07-22 15:05 UTC, godsflaw approved these changes

2022-09-20 19:31 UTC, brianmcmichael commented
Please avoid force-push.

Also, have we talked about getting this new MIP21 fork moved over to the makerdao github org? It's going to be difficult for the community to follow production MakerDAO code if it's in different orgs.

2022-09-20 19:33 UTC, brianmcmichael commented
Ah, it looks like most of this has been moved to https://github.com/makerdao/mip21-toolkit

Can you update the comments here to the relevant URLs?

2022-09-22 19:06 UTC, amusingaxl commented
> Can you update the comments here to the relevant URLs?

Done.

2022-11-01 18:27 UTC, brianmcmichael approved these changes

2022-11-01 18:27 UTC, merged